### ISSUE TITLE
Show HEXCODE within barcoder

### ISSUE THREAD

**Issue by Daxing1980** [Gaardsholt/barcoder#18]
Det ville være fedt om man kunne smide : 

HEX_CODE ind, og så viser den et billede af den farve.

Det ville være rigtig smart om man kunne skrive HEX_CODE1, HEX_CODE2 hvis man ville have et billede hvor man samlet viste 2 hexcoder (eller flere) i samme billede. F.eks. hvis man ville vise alle farver som er i en given kasse.

**Comment by Gaardsholt** [comment]
Så skulle det gerne være fixet :)
Ny release er blevet published: https://github.com/Gaardsholt/barcoder/releases/tag/v2.3.0
