### ISSUE TITLE
SHOW QR CODE WITH DIFFERENT BACKGROUND COLOUR

### ISSUE THREAD

**Issue by Daxing1980** [Gaardsholt/barcoder#19]
Det ville være fint om man kunne bestemme at QR koden skulle være en given farve.

**Comment by Gaardsholt** [comment]
Skal det være background eller foreground color du vil ændre?

Foreground = Sort
Background = Hvid
![Image of Yaktocat](http://barcoder.azurewebsites.net/image.png?text=aasdasd&type=2048&width=300&height=300&rotate=0)

**Comment by Gaardsholt** [comment]
Du kan nu tilføje en border color til dine hex billeder.
https://github.com/Gaardsholt/barcoder/releases/tag/v2.4.0
