### ISSUE TITLE
SHOW ICON WITHIN QR CODE

### ISSUE THREAD

**Issue by Daxing1980** [Gaardsholt/barcoder#20]
Om man kunne, så sætte et lille ikon ind som en del af QR koden ville være rigtig smart. F.eks. en stjerne for at vise at den pågældende qr kode er en "favorit".

**Comment by Gaardsholt** [comment]
Du kan nu tilføje et icon til QR koder.
https://github.com/Gaardsholt/barcoder/releases/tag/v2.5.0

Lad os sige at du bruger følgende URL i dag til at lave en QR kode: `http://localhost:16727/image.png?text=11111111&type=2048&width=300&height=300&rotate=0`
Så den eneste du skal gøre for at tilføje et icon er at tilføje `&logo=<link til dit icon>` i slutningen af linket.

Sådan her:
`http://localhost:16727/image.png?text=11111111&type=2048&width=300&height=300&rotate=0&logo=https://smallimg.pngkey.com/png/small/2-24221_google-chrome-apple-fedex-and-mcdonalds-are-some.png`
